### ISSUE TITLE
BDD: Configure CI to run BDD tests

### ISSUE THREAD

**Issue by tk3369** [Humans-of-Julia/TypeDBClient.jl#43]
Configure CI to run BDD process (pull [feature files](https://github.com/graknlabs/behaviour.git), [install Grakn](http://docs.grakn.ai/docs/running-grakn/install-and-run), and execute the tests)

**Comment by tk3369** [comment]
See https://github.com/Humans-of-Julia/GraknClient.jl/issues/30#issuecomment-779805189

Here's what I think would work:
1. Create a GitHub action to set up Grakn server
2. Create a GitHub action (or reuse an existing if available) to clone the BDD repo with feature files
3. Write a test script that execute the feature files using ExecutableSpecifications.jl 

As a developer, the local environment should have Grakn server and features available already. Then, doing `] test` from the REPL should just include BDD tests.

**Comment by mkschulze** [comment]
Perhaps we can use this here: https://github.com/marketplace/actions/github-action-for-bash

**Comment by mkschulze** [comment]
I created a GitHub Action here: https://github.com/Humans-of-Julia/GraknRunner

Not sure yet, if we can do it all in one, but would be ideal I think.

It can be easily included in a workflow file like:
```yaml
name: Grakn BDD runner
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to pull feature files, install Grakn, and execute the tests
    steps:
    - uses: actions/checkout@v2
    - id: foo
      uses: Humans-of-Julia/GraknRunner@0.1.0
      with:
        who-to-greet: 'Mark'
    - run: echo random-number ${{ steps.foo.outputs.random-number }}
      shell: bash
```
